# Generated by Django 4.1.2 on 2023-06-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservante', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('patente', models.CharField(max_length=6)),
                ('rut', models.CharField(max_length=9)),
                ('fecha_reserva', models.DateField()),
                ('horario', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], default=1, max_length=50)),
            ],
        ),
    ]
