# Generated by Django 4.1.2 on 2023-06-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='patente',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='reservante',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='rut',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
