# Generated by Django 4.1.2 on 2023-07-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_equipo',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('Notebook', 'Notebook'), ('All-In-one', 'All-In-one'), ('Celular', 'Celular'), ('Monitor', 'Monitor'), ('Otros', 'Otros')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='registro_equipo',
            name='departamento',
            field=models.CharField(choices=[('Seleccion Departamento', 'Seleccion Departamento'), ('Informatica', 'Informatica'), ('Turismo y Economia', 'Turismo y Economia'), ('DIDECO', 'DIDECO'), ('Tesoreria', 'Tesoreria'), ('Programa Familias', 'Programa Familias'), ('Registro Social de Hogares', 'Registro Social de Hogares'), ('Recursos Humanos', 'Recursos Humanos'), ('Alcalde', 'Alcalde'), ('Alcaldia', 'Alcaldia'), ('Secretaría Municipal', 'Secretaría Municipal'), ('Comunicaciones', 'Comunicaciones'), ('Oficina de Partes', 'Oficina de partes'), ('OMIL', 'OMIL'), ('Movilizacion y Transparecia', 'Movilizacion y Transparecia'), ('Direccion de Control', 'Direccion de Control'), ('Asesoria Juridica', 'Asesoria Juridica'), ('Secpla', 'Secpla'), ('Departamento de Obras', 'Departamento de Obras'), ('Emergencia y Seguridad Publica', 'Emergencia y Seguridad Publica'), ('Rentas y Patentes', 'Rentas y patentes'), ('Inspectores Municipales', 'Inspectores Municipales'), ('Departamento de Transito', 'Departamento de Transito'), ('Departamento de Administracion y Finanzas', 'Departamento de Administracion y Finanzas'), ('Ayuda Social', 'Ayuda Social'), ('Departamento de Salud', 'Departamento de Salud'), ('Adquisiciones', 'Adquisiciones'), ('Administracion y Finanzas', 'Administracion y Finanzas'), ('Biblioteca', 'Biblioteca')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='registro_equipo',
            name='nro_licencia_office',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registro_equipo',
            name='nro_licencia_windows',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registro_equipo',
            name='tipo_licencias_windows',
            field=models.CharField(choices=[('Seleccion Licencia de Windows', 'Seleccion Licencia de Windows'), ('Windows 7 Home Basic', 'Windows 7 Home Basic'), ('Windows 7 Home Premium', 'Windows 7 Home Premium'), ('Windows 7 Professional', 'Windows 7 Professional'), ('Windows 7 Ultimate', 'Windows 7 Ultimate'), ('Windows 7 Enterprise', 'Windows 7 Enterprise'), ('Windows 8 Single Language', 'Windows 8 Single Language'), ('Windows 8', 'Windows 8'), ('Windows 8 Pro', 'Windows 8 Pro'), ('Windows 8 Enterprise', 'Windows 8 Enterprise'), ('Windows 10 Home', 'Windows 10 Home'), ('Windows 10 Pro', 'Windows 10 Pro'), ('Windows 10 Enterprise', 'Windows 10 Enterprise'), ('Windows 11 Home', 'Windows 11 Home'), ('Windows 11 Pro', 'Windows 11 Pro'), ('Windows 11 Enterprise', 'Windows 11 Enterprise'), ('Licencia Vencida', 'Licencia Vencida'), ('Sin Licencia', 'Sin Licencia')], default=1, max_length=100),
        ),
    ]
