# Generated by Django 4.1.2 on 2023-07-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialApp', '0002_registro_equipo_tipo_dispositivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_equipo',
            name='contraseña',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='registro_equipo',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='registro_equipo',
            name='marca',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='registro_equipo',
            name='modelo',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='registro_equipo',
            name='rut',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
