# Generated by Django 4.1.2 on 2023-07-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialApp', '0004_rename_marca_registro_equipo_marca_y_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_equipo',
            name='contraseña',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='registro_equipo',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registro_equipo',
            name='marca_y_modelo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='registro_equipo',
            name='nro_licencia_office',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registro_equipo',
            name='nro_licencia_windows',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registro_equipo',
            name='rut',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
