# Generated by Django 4.1.2 on 2023-07-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serialApp', '0005_alter_registro_equipo_contraseña_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_equipo',
            old_name='marca_y_modelo',
            new_name='marca_modelo',
        ),
    ]
