# Generated by Django 4.1.2 on 2023-07-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serialApp', '0002_alter_registro_equipo_tipo_dispositivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_equipo',
            name='rut',
        ),
    ]
