# Generated by Django 4.1.2 on 2023-06-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservante', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fechareserva', models.DateField()),
                ('horareserva', models.TimeField()),
                ('estado', models.CharField(choices=[('Reservado', 'Reservado'), ('Completada', 'Completada'), ('Anulada', 'Anulada'), ('No asisten', 'No asisten')], default=1, max_length=50)),
                ('numeropersonas', models.IntegerField()),
                ('observacion', models.CharField(max_length=100)),
            ],
        ),
    ]
