# Generated by Django 4.1.2 on 2023-07-24 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serialApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_equipo',
            name='fecha_ingreso_del_registro',
        ),
        migrations.RemoveField(
            model_name='registro_equipo',
            name='rut',
        ),
        migrations.AddField(
            model_name='registro_equipo',
            name='fecha_de_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro_equipo',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('Notebook', 'Notebook'), ('All-In-one', 'All-In-one'), ('Celular', 'Celular'), ('Monitor', 'Monitor'), ('Impresora', 'Impresora'), ('Otros', 'Otros')], default=1, max_length=100),
        ),
    ]
