# Generated by Django 4.1.2 on 2023-07-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialApp', '0002_remove_registro_equipo_fecha_ingreso_del_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_equipo',
            name='nro_licencia_office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registro_equipo',
            name='nro_licencia_windows',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
