# Generated by Django 4.1.2 on 2023-08-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serialApp', '0002_alter_registro_equipo_tipo_dispositivo'),
        ('serialApp', '0002_equipo_licencia_delete_registro_equipo'),
        ('serialApp', '0003_alter_registro_equipo_nro_licencia_office_and_more'),
    ]

    operations = [
    ]
