# Generated by Django 4.1 on 2023-02-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=9)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default=1, max_length=50)),
                ('contrato', models.CharField(choices=[('Por Faena', 'Por Faena'), ('Plazo Fijo', 'Plazo Fijo'), ('Part Time', 'Part Time'), ('Contrato Indefinido', 'Contrato Indefinido'), ('Contrato para Practicante', 'Contrato para Practicante'), ('Contrato para extranjero', 'Contrato para extranjero'), ('Contrato para arte y espectaculo', 'Contrato para arte y espectaculo'), ('Contrato por honorarios', 'Contrato por honorarios')], default=1, max_length=50)),
            ],
        ),
    ]
