# Generated by Django 4.1 on 2023-02-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default=1, max_length=50)),
                ('contrato', models.CharField(choices=[('Plazo Fijo', 'Plazo Fijo'), ('Part Time', 'Part Time'), ('Por Faena', 'Por Faena'), ('Contrato Indefinido', 'Contrato Indefinido'), ('Contrato para Practicante', 'Contrato para Practicante'), ('Contrato para extranjero', 'Contrato para extranjero'), ('Contrato para arte y espectaculo', 'Contrato para arte y espectaculo'), ('Contrato por honorarios', 'Contrato por honorarios')], default=1, max_length=50)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia Bancaria', 'Transferencia Bancaria')], default=1, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
    ]
