# Generated by Django 4.1.2 on 2023-03-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forma_de_Pago',
        ),
        migrations.RenameField(
            model_name='datos_empleado',
            old_name='Cotizacion_Voluntaria_Solud_Uf',
            new_name='Cotizacion_Voluntaria_Salud_Uf',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
