# Generated by Django 4.1.2 on 2023-05-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apv',
            name='Ahorro_Pesos',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='apv',
            name='Ahorro_UF',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='apv',
            name='Deposito_Convenido',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='apv',
            name='Forma_Pago_Apv',
            field=models.CharField(blank=True, choices=[('--Por favor Seleccione--', '--Por favor Seleccione--'), ('Directa', 'Directa'), ('Indirecta', 'Indirecta')], default=1, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='apv',
            name='Institucion_Apv',
            field=models.CharField(blank=True, choices=[('--Por favor Seleccione--', '--Por favor Seleccione--'), ('No cotiza A.P.V', 'No cotiza A.P.V'), ('Cuprum', 'Cuprum'), ('Habitat', 'Habitat'), ('Provida', 'Provida'), ('Planvital', 'Planvital'), ('Capital', 'Capital'), ('Modelo', 'Modelo'), ('ABN AMRO (CHILE) SEGUROS DE VIDA S.A', 'ABN AMRO (CHILE) SEGUROS DE VIDA S.A'), ('AGF ALLIANZ CHILE COMPAÑIA DE SEGUROS VIDA S.A', 'AGF ALLIANZ CHILE COMPAÑIA DE SEGUROS VIDA S.A'), ('SANTANDER SEGUROS DE VIDA S.A', 'SANTANDER SEGUROS DE VIDA S.A'), ('BCI SEGUROS VIDA S.A', 'BCI SEGUROS VIDA S.A'), ('BANCHILE SEGUROS DE VIDA S.A', 'BANCHILE SEGUROS DE VIDA S.A'), ('BBVA SEGUROS DE VIDA S.A', 'BBVA SEGUROS DE VIDA S.A'), ('BICE VIDA COMPAÑIA DE SEGUROS S.A', 'BICE VIDA COMPAÑIA DE SEGUROS S.A'), ('CHILENA CONSOLIDADA SEGUROS DE VIDA S.A', 'CHILENA CONSOLIDADA SEGUROS DE VIDA S.A'), ('CIGNA COMPAÑIA DE SEGUROS DE VIDA S.A', 'CIGNA COMPAÑIA DE SEGUROS DE VIDA S.A'), ('CN LIFE, COMPAÑIA DE SEGUROS DE VIDA S.A', 'CN Life, COMPAÑIA DE SEGUROS DE VIDA S.A'), ('COMPAÑIA DE SEGUROS DE VIDA CARDIF S.A', 'COMPAÑIA DE SEGUROS DE VIDA CARDIF S.A'), ('CIA DE SEG. DE VIDA CONSORCIO NACIONAL DE SEG S.A', 'CIA DE SEG. DE VIDA CONSORCIO NACIONAL DE SEG S.A'), ('COMPAÑIA DE SEGUROS DE VIDA HUELEN S.A', 'COMPAÑIA DE SEGUROS DE VIDA HUELEN S.A'), ('COMPAÑIA DE SEGUROS DE VIDA VITALIS S.A', 'COMPAÑIA DE SEGUROS DE VIDA VITALIS S.A'), ('COMPAÑIA DE SEGUROS CORPVIDA S.A', 'COMPAÑIA DE SEGUROS CORPVIDA S.A'), ('EUROAMERICA SEGUROS DE VIDA S.A', 'EUROAMERICA SEGUROS DE VIDA S.A'), ('SEGUROS DE VIDA SURA S.A', 'SEGUROS DE VIDA SURA S.A'), ('METLIFE CHILE SEGUROS DE VIDA S.A', 'METLIFE CHILE SEGUROS DE VIDA S.A'), ('MAPFRE COMPAÑIA DE SEGUROS DE VIDA DE CHILE S.A', 'MAPFRE COMPAÑIA DE SEGUROS DE VIDA DE CHILE S.A'), ('MUTUAL DE SEGUROS DE CHILE', 'MUTUAL DE SEGUROS DE CHILE'), ('MUTUALIDAD DE CARABINEROS', 'MUTUALIDAD DE CARABINEROS'), ('MUTUALIDAD DEL EJERCITO Y AVIACION', 'MUTUALIDAD DEL EJERCITO Y AVIACION'), ('OHIO NATIONAL SEGUROS DE VIDA S.A', 'OHIO NATIONAL SEGUROS DE VIDA S.A'), ('PRINCIPAL COMPAÑIA DE SEGUROS DE VIDA CHILE S.A', 'PRINCIPAL COMPAÑIA DE SEGUROS DE VIDA CHILE S.A'), ('RENTA NACIONAL COMPAÑIA DE SEGUROS DE VIDA S.A', 'RENTA NACIONAL COMPAÑIA DE SEGUROS DE VIDA S.A'), ('SEGUROS DE VIDA SECURITY PREVISION S.A', 'SEGUROS DE VIDA SECURITY PREVISION S.A'), ('COMPAÑIA DE SEGUROS GENERALES PENTA-SECURITY S.A', 'COMPAÑIA DE SEGUROS GENERALES PENTA-SECURITY S.A'), ('PENTA VIDA COMPAÑIA DE SEGUROS DE VIDA S.A', 'PENTA VIDA COMPAÑIA DE SEGUROS DE VIDA S.A'), ('ACE SEGUROS S.A', 'ACE SEGUROS S.A'), ('BANDESARROLLO ADMINISTRADORA GENERAL DE FONDOS S.A', 'BANDESARROLLO ADMINISTRADORA GENERAL DE FONDOS S.A'), ('BBVA ASSET MANAGEMENT ADMINISTRADORA GENERAL DE FONDOS  S.A', 'BBVA ASSET MANAGEMENT ADMINISTRADORA GENERAL DE FONDOS S.A'), ('BCI ASSET MANAGEMENT ADMINISTRADORA GENERAL DE FONDOS S.A', 'BCI ASSET MANAGEMENT ADMINISTRADORA GENERAL DE FONDOS S.A'), ('BICE INVERSIONES ADMINISTRADORA GENERAL DE FONDOS S.A', 'BICE INVERSIONES ADMINISTRADORA GENERAL DE FONDOS S.A'), ('BTG PACTUAL CHILE S.A AGF', 'BTG PACTUAL CHILE S.A AGF'), ('CORPBANCA ADMINISTRADORA GENERAL DE FONDOS S.A', 'CORPBANCA ADMINISTRADORA GENERAL DE FONDOS S.A'), ('LARRAIN VIAL S.A CORREDORA DE BOLSA', 'LARRAIN VIAL S.A CORREDORA DE BOLSA'), ('PRINCIPAL ADMINISTRADORA GENERAL DE FONDOS S.A', 'PRINCIPAL ADMINISTRADORA GENERAL DE FONDOS S.A'), ('SANTANDER ASSET MANAGEMENT S.A ADM. GENERAL DE FONDOS', 'SANTANDER ASSET MANAGEMENT S.A ADM. GENERAL DE FONDOS'), ('SCOTIA SUD AMERICANO ADMINISTRADORA DE FONDOS MUTUOS S.A', 'SCOTIA SUD AMERICANO ADMINISTRADORA DE FONDOS MUTUOS S.A'), ('ADMINISTRADORA GENERAL DE FONDOS SECURITY S.A', 'ADMINISTRADORA GENERAL DE FONDOS SECURITY S.A'), ('CRUZ DEL SUR CORREDORA DE BOLSA S.A', 'CRUZ DEL SUR CORREDORA DE BOLSA S.A'), ('BANCHILE CORREDORES DE BOLSA S.A', 'BANCHILE CORREDORES DE BOLSA S.A'), ('ZURICH ADMINISTRADORA GENERAL DE FONDOS S.A', 'ZURICH ADMINISTRADORA GENERAL DE FONDOS S.A'), ('ITAU CHILE ADMINISTRADORA GENERAL DE FONDOS S.A', 'ITAU CHILE ADMINISTRADORA GENERAL DE FONDOS S.A'), ('PENTA ADMINISTRADORA GENERAL DE FONDOS S.A', 'PENTA ADMINISTRADORA GENERAL DE FONDOS S.A'), ('CORREDORES DE BOLSA SURA S.A', 'CORREDORES DE BOLSA SURA S.A'), ('BTG PACTUAL CHILE S.A CORREDORES DE BOLSA', 'BTG PACTUAL CHILE S.A CORREDORES DE BOLSA'), ('BANCOESTADO S.A ADMINISTRADORA GENERAL DE FONDOS', 'BANCOESTADO S.A ADMINISTRADORA GENERAL DE FONDOS'), ('ING ADMINISTRADORA GENERAL DE FONDOS S.A', 'ING ADMINISTRADORA GENERAL DE FONDOS S.A'), ('SCOTIA SUD AMERICANO CORREDORES DE BOLSA S.A', 'SCOTIA SUD AMERICANO CORREDORES DE BOLSA S.A'), ('BICE INVERSIONES CORREDORES DE BOLSA S.A', 'BICE INVERSIONES CORREDORES DE BOLSA S.A'), ('CRUZ DEL SUR ADMINISTRADORA GENERAL DE FONDOS S.A', 'CRUZ DEL SUR ADMINISTRADORA GENERAL DE FONDOS S.A'), ('EUROAMERICA ADMINISTRADORA GENERAL DE FONDOS S.A', 'EUREUROAMERICA ADMINISTRADORA GENERAL DE FONDOS S.A'), ('LARRAIN VIAL ADMINISTRADORA GENERAL DE FONDOS S.A', 'LARRAIN VIAL ADMINISTRADORA GENERAL DE FONDOS S.A'), ('BBVA Banco Bhif', 'BBVA Banco Bhif'), ('Banco Ripley', 'Banco Ripley'), ('Banco ScotiaBank', 'Banco ScotiaBank'), ('Banco Santander Santiago', 'Banco Santander Santiago'), ('CAJA DE COMPENSACION LOS ANDES', 'CAJA DE COMPENSACION LOS ANDES')], default=1, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='apv',
            name='Nro_Contrato_Apv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apv',
            name='Regimen_Apv',
            field=models.CharField(blank=True, choices=[('--Por favor Seleccione--', '--Por favor Seleccione--'), ('Regimen A', 'Regimen A'), ('Regimen B', 'Regimen B')], default=1, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='datos_empleado',
            name='Descuento_Prestamo_SII',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_empleado',
            name='Pensionado_por_Invalidez',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_empleado',
            name='Profesional',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_empleado',
            name='Tecnico_Extranjero',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='Dias_Descontados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='Dias_Licencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='Director_de_Empresa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='Profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='Sin_Seguro_Cesantia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='Trabajador_Agricola',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='no_imponibles',
            name='Colacion',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='no_imponibles',
            name='Desgaste_Herramientas',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='no_imponibles',
            name='Movilizacion',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='no_imponibles',
            name='Perdida_Caja',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='no_imponibles',
            name='Trabajo_Remoto',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='regimen_provisional',
            name='Afp',
            field=models.CharField(blank=True, choices=[('--Por favor Seleccione--', '--Por favor Seleccione--'), ('No esta en AFP', 'No esta en AFP'), ('Cuprum', 'Cuprum'), ('Habitat', 'Habitat'), ('Provida', 'Provida'), ('Planvital', 'Planvital'), ('Capital', 'Capital'), ('Modelo', 'Modelo'), ('Uno', 'Uno')], default=1, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='regimen_provisional',
            name='Ahorro_Voluntario_Afp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='regimen_provisional',
            name='Ahorro_imponible',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='regimen_provisional',
            name='Desea_APV',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regimen_provisional',
            name='Ex_caja',
            field=models.CharField(blank=True, choices=[('--Por favor Seleccione--', '--Por favor Seleccione--'), ('No pertenece al IPS', 'No pertenece al IPS'), ('Empart - Regimen 1', 'Empart - Regimen 1'), ('Empart - Regimen 2', 'Empart - Regimen 2'), ('Empart - Regimen 3', 'Empart - Regimen 3'), ('Empart - Regimen 4', 'Empart - Regimen 4'), ('Empart - Regimen 6', 'Empart - Regimen 6'), ('Bancaria - Regimen 1', 'Bancaria - Regimen 1'), ('Bancaria - Regimen 2', 'Bancaria - Regimen 2'), ('Bancaria - Regimen 3', 'Bancaria - Regimen 3'), ('Bancaria - Regimen 14', 'Bancaria - Regimen 14'), ('Bancaria - Regimen 21', 'Bancaria - Regimen 21'), ('Bancaria - Regimen 34', 'Bancaria - Regimen 34'), ('Caprebech - Regimen 1', 'Caprebech - Regimen 1'), ('Caprebech - Regimen 3', 'Caprebech - Regimen 3'), ('Caprebech - Regimen 14', 'Caprebech - Regimen 14'), ('Caprebech - Regimen 21', 'Caprebech - Regimen 21'), ('Caprebech - Regimen 34', 'Caprebech - Regimen 34'), ('Capremer - Regimen 1', 'Capremer - Regimen 1'), ('Capremer - Regimen 2', 'Capremer - Regimen 2'), ('Capremer - Regimen 3', 'Capremer - Regimen 3'), ('Capremer - Regimen 4', 'Capremer - Regimen 4'), ('Capremer - Regimen 5', 'Capremer - Regimen 5'), ('Capremer - Regimen 6', 'Capremer - Regimen 6'), ('Capremer - Regimen 8', 'Capremer - Regimen 8'), ('Triomar - Regimen 1', 'Triomar - Regimen 1'), ('Triomar - Regimen 2', 'Triomar - Regimen 2'), ('Triomar - Regimen 3', 'Triomar - Regimen 3'), ('Triomar - Regimen 4', 'Triomar - Regimen 4'), ('Hipica Nacional - Regimen 1', 'Hipica Nacional - Regimen 1'), ('Hipica Nacional - Regimen 2', 'Hipica Nacional - Regimen 2'), ('Hipica Nacional - Regimen 3', 'Hipica Nacional - Regimen 3'), ('Hipica Nacional - Regimen 4', 'Hipica Nacional - Regimen 4'), ('Servicios de Seguro  Social - Regimen 1', 'Servicios de Seguro Social - Regimen 1'), ('Servicios de Seguro  Social - Regimen 2', 'Servicios de Seguro Social - Regimen 2'), ('Empleados de Emos - Regimen 1', 'Empleados de Emos - Regimen 1'), ('Obreros de Emos - Regimen 1', 'Obreros de Emos - Regimen 1'), ('Caja Ferro - Regimen 2', 'Caja Ferro - Regimen 2'), ('Caja Ferro - Regimen 3', 'Caja Ferro - Regimen 3'), ('Caja Ferro - Regimen 4', 'Caja Ferro - Regimen 4'), ('Caja Ferro - Regimen 5', 'Caja Ferro - Regimen 5'), ('Caja Ferro - Regimen 7', 'Caja Ferro - Regimen 7'), ('Canaempu: Publicos - Regimen 1', 'Canaempu: Publicos - Regimen 1'), ('Canaempu: Publicos - Regimen 2', 'Canaempu: Publicos - Regimen 2'), ('Canaempu: Publicos - Regimen 3', 'Canaempu: Publicos - Regimen 3'), ('Canaempu: Publicos - Regimen 5', 'Canaempu: Publicos - Regimen 5'), ('Canaempu: Publicos - Regimen 6', 'Canaempu: Publicos - Regimen 6'), ('Canaempu: Publicos - Regimen 8', 'Canaempu: Publicos - Regimen 8'), ('Canaempu: Publicos - Regimen 9', 'Canaempu: Publicos - Regimen 9'), ('Canaempu: Publicos - Regimen 10', 'Canaempu: Publicos - Regimen 10'), ('Canaempu: Publicos - Regimen 11', 'Canaempu: Publicos - Regimen 11'), ('Canaempu: Publicos - Regimen 12', 'Canaempu: Publicos - Regimen 12'), ('Canaempu: Publicos - Regimen 21', 'Canaempu: Publicos - Regimen 21'), ('Canaempu: Publicos - Regimen 22', 'Canaempu: Publicos - Regimen 22'), ('Canaempu: Publicos - Regimen 23', 'Canaempu: Publicos - Regimen 23'), ('Canaempu: Publicos - Regimen 25', 'Canaempu: Publicos - Regimen 25'), ('Canaempu: Publicos - Regimen 26', 'Canaempu: Publicos - Regimen 26'), ('Canaempu: Publicos - Regimen 28', 'Canaempu: Publicos - Regimen 28'), ('Canaempu: Publicos - Regimen 29', 'Canaempu: Publicos - Regimen 29'), ('Canaempu: Publicos - Regimen 30', 'Canaempu: Publicos - Regimen 30'), ('Canaempu: Publicos - Regimen 31', 'Canaempu: Publicos - Regimen 31'), ('Canaempu: Publicos - Regimen 32', 'Canaempu: Publicos - Regimen 32'), ('Canaempu: Publicos - Regimen 38', 'Canaempu: Publicos - Regimen 38'), ('Canaempu: Periodistas - Regimen 1', 'Canaempu: Periodistas - Regimen 1'), ('Canaempu: Periodistas - Regimen 2', 'Canaempu: Periodistas - Regimen 2'), ('Canaempu: Periodistas - Regimen 3', 'Canaempu: Periodistas - Regimen 3'), ('Canaempu: Periodistas - Regimen 4', 'Canaempu: Periodistas - Regimen 4'), ('Canaempu: Periodistas - Regimen 5', 'Canaempu: Periodistas - Regimen 5'), ('Canaempu: Periodistas - Regimen 6', 'Canaempu: Periodistas - Regimen 6'), ('Canaempu: Periodistas - Regimen 7', 'Canaempu: Periodistas - Regimen 7'), ('Canaempu: Periodistas - Regimen 8', 'Canaempu: Periodistas - Regimen 8'), ('Canaempu: Periodistas - Regimen 11', 'Canaempu: Periodistas - Regimen 11'), ('Canaempu: Periodistas - Regimen 12', 'Canaempu: Periodistas - Regimen 12'), ('Canaempu: Periodistas - Regimen 13', 'Canaempu: Periodistas - Regimen 13'), ('Canaempu: Periodistas - Regimen 14', 'Canaempu: Periodistas - Regimen 14'), ('Canaempu: Periodistas - Regimen 15', 'Canaempu: Periodistas - Regimen 15'), ('Canaempu: Periodistas - Regimen 16', 'Canaempu: Periodistas - Regimen 16'), ('Canaempu: Periodistas - Regimen 17', 'Canaempu: Periodistas - Regimen 17'), ('Canaempu: Periodistas - Regimen 18', 'Canaempu: Periodistas - Regimen 18'), ('Canaempu: Periodistas - Regimen 21', 'Canaempu: Periodistas - Regimen 21'), ('Canaempu: Periodistas - Regimen 22', 'Canaempu: Periodistas - Regimen 22'), ('Canaempu: Periodistas - Regimen 23', 'Canaempu: Periodistas - Regimen 23'), ('Canaempu: Periodistas - Regimen 24', 'Canaempu: Periodistas - Regimen 24'), ('Canaempu: Periodistas - Regimen 25', 'Canaempu: Periodistas - Regimen 25'), ('Canaempu: Periodistas - Regimen 26', 'Canaempu: Periodistas - Regimen 26'), ('Canaempu: Periodistas - Regimen 31', 'Canaempu: Periodistas - Regimen 31'), ('Canaempu: Periodistas - Regimen 32', 'Canaempu: Periodistas - Regimen 32'), ('Canaempu: Periodistas - Regimen 33', 'Canaempu: Periodistas - Regimen 33'), ('Canaempu: Periodistas - Regimen 34', 'Canaempu: Periodistas - Regimen 34'), ('Copremusa EE - Regimen 1', 'Copremusa EE - Regimen 1'), ('Copremusa EE - Regimen 2', 'Copremusa EE - Regimen 2'), ('Copremusa EE - Regimen 3', 'Copremusa EE - Regimen 3'), ('Caja de Prevision Social de EE - Regimen 1', 'Caja de Prevision Social de EE - Regimen 1'), ('Caja de Prevision Social de EE - Regimen 2', 'Caja de Prevision Social de EE - Regimen 2'), ('EE Municipales de la Republica - Regimen 1', 'EE Municipales de la Republica - Regimen 1'), ('EE Municipales de la Republica - Regimen 2', 'EE Municipales de la Republica - Regimen 2'), ('EE Municipales de la Republica - Regimen 3', 'EE Municipales de la Republica - Regimen 3'), ('EE Municipales de la Republica - Regimen 4', 'EE Municipales de la Republica - Regimen 4'), ('OO Municipales de la Republica - Regimen 1', 'OO Municipales de la Republica - Regimen 1'), ('OO Municipales de la Republica - Regimen 2', 'OO Municipales de la Republica - Regimen 2'), ('OO Municipales de la Republica - Regimen 3', 'OO Municipales de la Republica - Regimen 3'), ('Diomp - Regimen 1', 'Diomp - Regimen 1'), ('EE Salitre - Regimen 1', 'EE Salitre - Regimen 1'), ('EE Salitre - Regimen 2', 'EE Salitre - Regimen 2'), ('Sec. Esp.Prevision Empleados - Regimen 1', 'Sec. Esp.Prevision Empleados - Regimen 1'), ('Sec. Esp.Prevision Empleados - Regimen 2', 'Sec. Esp.Prevision Empleados - Regimen 2'), ('Caja de Prevision Gildemeister - Regimen 1', 'Caja de Prevision Gildemeister - Regimen 1'), ('Caja de Prevision Gildemeister - Regimen 2', 'Caja de Prevision Gildemeister - Regimen 2'), ('Mauricio, Hochschild - Regimen 1', 'Mauricio, Hochschild - Regimen 1'), ('Mauricio, Hochschild - Regimen 2', 'Mauricio, Hochschild - Regimen 2'), ('Secgasco - Regimen 1', 'Secgasco - Regimen 1'), ('Secgasco - Regimen 2', 'Secgasco - Regimen 2')], default=1, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='regimen_provisional',
            name='Tasa_Ex_caja',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
