# Generated by Django 4.1.2 on 2023-04-21 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tramo', models.CharField(choices=[('--Por favor Seleccione--', '--Por favor Seleccione--'), ('Primer Tramo A', 'Primer Tramo A'), ('Segundo Tramo B', 'Segundo Tramo B'), ('Tercer Tramo C', 'Tercer Tramo C'), ('Sin Derecho D', 'Sin Derecho D')], default=1, max_length=500)),
                ('Cargas_simples', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10)),
                ('Cargas_maternales', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10)),
                ('Cargas_por_invalidez', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10)),
                ('Monto_retroactivo', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10)),
                ('Monto_reintegro', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10)),
                ('Datos_Empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.datos_empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Factor_impuesto_unico_primera_categoria', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10)),
                ('Cantidad_a_rebajar', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10)),
                ('Datos_Empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.datos_empleado')),
            ],
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='Datos_Empleado',
        ),
        migrations.RemoveField(
            model_name='movimiento_personal',
            name='Movimientos',
        ),
        migrations.AddField(
            model_name='movimiento_personal',
            name='Datos_Empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.datos_empleado'),
        ),
        migrations.AlterField(
            model_name='movimiento_personal',
            name='Movimiento_Personal',
            field=models.CharField(choices=[('--Por favor Seleccione--', '--Por favor Seleccione--'), ('Contratacion a plaazo indefinido', 'Contratacion a plaazo indefinido'), ('Retiro', 'Retiro'), ('Subsidios (Licencia)', 'Subsidios (Licencia)'), ('Permiso sin goce de sueldos', 'Permiso sin goce de sueldos'), ('Incorporacion en el lugar de trabajo', 'Incorporacion en el lugar de trabajo'), ('Accidentes del trabajo', 'Accidentes del trabajo'), ('Contratacion a plazo fijo', 'Contratacion a plazo fijo'), ('Cambio contrato plazo fijo a plazo indefinido', 'Cambio contrato plazo fijo a plazo indefinido'), ('Otros movimientos (ausentismos)', 'Otros movimientos (ausentismos)'), ('Reliquidacion, premio, bono', 'Reliquidacion, premio, bono'), ('Suspension de contrato acto de autoridad (Ley N°21.227)', 'Suspension de contrato acto de autoridad (Ley N°21.227)'), ('Suspension de contrato por pacto (Ley N° 21.227)', 'Suspension de contrato por pacto (Ley N° 21.227)'), ('Reduccion de jornada (Ley N° 21.227)', 'Reduccion de jornada (Ley N° 21.227)')], default=1, max_length=500),
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Movimientos',
        ),
    ]
