# Generated by Django 4.1.2 on 2023-04-10 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forma_de_pago',
            name='Datos_Empleado',
        ),
        migrations.RemoveField(
            model_name='liquidacion',
            name='Datos_Empleado',
        ),
        migrations.RemoveField(
            model_name='no_imponibles',
            name='Datos_Empleado',
        ),
        migrations.RemoveField(
            model_name='regimen_provisional',
            name='APV',
        ),
        migrations.RemoveField(
            model_name='regimen_provisional',
            name='Datos_Empleado',
        ),
        migrations.RemoveField(
            model_name='salud',
            name='Datos_Empleado',
        ),
        migrations.AddField(
            model_name='datos_empleado',
            name='APV',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.apv'),
        ),
        migrations.AddField(
            model_name='datos_empleado',
            name='Forma_de_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.forma_de_pago'),
        ),
        migrations.AddField(
            model_name='datos_empleado',
            name='Liquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.liquidacion'),
        ),
        migrations.AddField(
            model_name='datos_empleado',
            name='No_Imponibles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.no_imponibles'),
        ),
        migrations.AddField(
            model_name='datos_empleado',
            name='Regimen_Provisional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.regimen_provisional'),
        ),
        migrations.AddField(
            model_name='datos_empleado',
            name='Salud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.salud'),
        ),
    ]
