# Generated by Django 4.1.2 on 2023-04-10 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0002_remove_forma_de_pago_datos_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_empleado',
            name='APV',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.apv'),
        ),
        migrations.AlterField(
            model_name='datos_empleado',
            name='Forma_de_pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.forma_de_pago'),
        ),
        migrations.AlterField(
            model_name='datos_empleado',
            name='Liquidacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.liquidacion'),
        ),
        migrations.AlterField(
            model_name='datos_empleado',
            name='No_Imponibles',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.no_imponibles'),
        ),
        migrations.AlterField(
            model_name='datos_empleado',
            name='Salud',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.salud'),
        ),
    ]
