# Generated by Django 4.1.2 on 2023-03-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0002_delete_forma_de_pago_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='No_Imponibles',
        ),
        migrations.AddField(
            model_name='datos_empleado',
            name='Colacion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='datos_empleado',
            name='Desgaste_Herramientas',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='datos_empleado',
            name='Movilizacion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='datos_empleado',
            name='Perdida_Caja',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='datos_empleado',
            name='Trabajo_Remoto',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
