# Generated by Django 4.1.2 on 2023-04-10 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0003_alter_datos_empleado_apv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_empleado',
            name='APV',
        ),
        migrations.RemoveField(
            model_name='datos_empleado',
            name='Forma_de_pago',
        ),
        migrations.RemoveField(
            model_name='datos_empleado',
            name='Liquidacion',
        ),
        migrations.RemoveField(
            model_name='datos_empleado',
            name='No_Imponibles',
        ),
        migrations.RemoveField(
            model_name='datos_empleado',
            name='Regimen_Provisional',
        ),
        migrations.RemoveField(
            model_name='datos_empleado',
            name='Salud',
        ),
        migrations.AddField(
            model_name='apv',
            name='Datos_Empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.datos_empleado'),
        ),
        migrations.AddField(
            model_name='forma_de_pago',
            name='Datos_Empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.datos_empleado'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='Datos_Empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.datos_empleado'),
        ),
        migrations.AddField(
            model_name='no_imponibles',
            name='Datos_Empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.datos_empleado'),
        ),
        migrations.AddField(
            model_name='regimen_provisional',
            name='Datos_Empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.datos_empleado'),
        ),
        migrations.AddField(
            model_name='salud',
            name='Datos_Empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.datos_empleado'),
        ),
    ]
