# Generated by Django 4.1 on 2023-03-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0004_libro_rem_electronico_remove_empleado_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_empleado',
            name='Fecha_Nacimiento',
            field=models.DateField(null=True),
        ),
    ]
