# Generated by Django 4.1 on 2023-03-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0005_datos_empleado_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_empleado',
            name='Estado_civil',
            field=models.CharField(choices=[('--Seleccione el estado civil--', '--Seleccione el estado civil--'), ('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo')], default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='datos_empleado',
            name='Nombres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datos_empleado',
            name='Sexo',
            field=models.CharField(choices=[('--Seleccione su genero--', '--Seleccione su genero--'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No binario', 'No binario'), ('Prefiero no decirlo', 'Prefiero no decirlo')], default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='datos_empleado',
            name='Tipo_de_impuesto_unico',
            field=models.CharField(choices=[('--Seleccione el tipo de impuesto--', '--Seleccione el tipo de impuesto--'), ('Normal', 'Normal'), ('Trabajador Agricola', 'Trabajador Agricola')], default=1, max_length=500),
        ),
    ]
