# Generated by Django 4.1 on 2023-03-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0006_alter_datos_empleado_estado_civil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='Datos_Empleado',
        ),
        migrations.DeleteModel(
            name='Libro_Rem_Electronico',
        ),
        migrations.AddField(
            model_name='datos_empleado',
            name='Tipo_Jornada_Trabajo',
            field=models.CharField(choices=[('--Seleccione el tipo de jornada--', '--Seleccione el tipo de jornada--'), ('ORDINARIA - ART 22 (45 Horas)', 'ORDINARIA-ART 22 (45 Horas)'), ('PARCIAL - ART 40 BIS (30 Horas max)', 'PARCIAL-ART 40 BIS (30 Horas max)'), ('EXTRAORDINARIA - ART 30 (sobretiempo)', 'EXTRAORDINARIA-ART 30 (sobretiempo)'), ('ESPECIAL - ART 38 INCISO 5 (trabajo fuerza mayor)', 'ESPECIAL - ART 38 INCISO 5 (trabajo fuerza mayor)'), ('ESPECIAL - ART 23 (NAVIERO)', 'ESPECIAL - ART 23 (NAVIERO)'), ('ESPECIAL - ART 106 (NAVIERO)', 'ESPECIAL - ART 106 (NAVIERO)'), ('ESPECIAL - ART 152 TER D (tripulantes de vuelo)', 'ESPECIAL - ART 152 TER D (tripulantes de vuelo)'), ('ESPECIAL - ART 152 TER F (tripulantes de vuelo)', 'ESPECIAL - ART 152 TER F (tripulantes de vuelo)'), ('ESPECIAL - ART 25 (locomocion colectiva interurbana)', 'ESPECIAL - ART 25 (locomocion colectiva interurbana)'), ('ESPECIAL - ART 25 BIS (carga terrestre interurbana)', 'ESPECIAL - ART 25 BIS (carga terrestre interurbana)'), ('ESPECIAL - ART 149 (trabajadores de casa particular)', 'ESPECIAL - ART 149 (trabajadores de casa particular)'), ('ESPECIAL - ART 149 INCISO 2 (trabajadores de casa particular)', 'ESPECIAL - ART 149 INCISO 2 (trabajadores de casa particular)'), ('ESPECIAL - ART 152 BIS (cuerpos de bomberos)', 'ESPECIAL - ART 152 BIS (cuerpos de bomberos)'), ('ESPECIAL - ART 36 145-D (artes y espectaculos)', 'ESPECIAL - ART 36 145-D (artes y espectaculos)'), ('ESPECIAL - ART 22 INCISO FINAL (deportistas profesionales)', 'ESPECIAL - ART 22 INCISO FINAL (deportistas profesionales)'), ('BISEMANAL - ART 149 INCISO 2 (trabajadores de casa particular)', 'BISEMANAL - ART 149 INCISO 2 (trabajadores de casa particular)'), ('JORNADA EXCEPCIONAL - ART 38 INCISO FINAL (trabajo fuerza mayor)', 'JORNADA EXCEPCIONAL - ART 38 INCISO FINAL (trabajo fuerza mayor)'), ('EXENTA - ART 22 (sin limitacion de jornada)', 'EXENTA - ART 22 (sin limitacion de jornada)')], default=1, max_length=500),
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
