# Generated by Django 4.1 on 2023-03-01 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0007_remove_empleado_datos_empleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('ID', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('Datos_Empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_app.datos_empleado')),
            ],
        ),
    ]
