# Generated by Django 4.1.2 on 2023-03-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0008_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_empleado',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
