# Generated by Django 4.1 on 2023-01-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialApp', '0002_remove_proyecto_fecha_termino_alter_proyecto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
