# Generated by Django 4.1 on 2023-01-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialApp', '0003_proyecto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='proyectos'),
        ),
    ]
