# Generated by Django 4.1.2 on 2023-02-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialApp', '0004_alter_proyecto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='projects/'),
        ),
    ]
