# Generated by Django 4.1 on 2023-02-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='contrato',
            field=models.CharField(choices=[('--Seleccion Contrato--', '--Seleccion Contrato--'), ('Plazo Fijo', 'Plazo Fijo'), ('Part Time', 'Part Time'), ('Por Faena', 'Por Faena'), ('Contrato Indefinido', 'Contrato Indefinido'), ('Contrato para Practicante', 'Contrato para Practicante'), ('Contrato para extranjero', 'Contrato para extranjero'), ('Contrato para arte y espectaculo', 'Contrato para arte y espectaculo'), ('Contrato por honorarios', 'Contrato por honorarios')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('--Seleccion Estado--', '--Seleccion Estado--'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='metodo_pago',
            field=models.CharField(choices=[('--Metodo Pago--', '--Metodo Pago--'), ('Efectivo', 'Efectivo'), ('Transferencia Bancaria', 'Transferencia Bancaria')], default=1, max_length=50),
        ),
    ]
