# Generated by Django 4.1 on 2023-02-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0002_alter_empleado_contrato_alter_empleado_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Empleado',
            fields=[
                ('Rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Comuna', models.CharField(max_length=100)),
                ('Sexo', models.CharField(choices=[('--Seleccione su genero--', '--Seleccione su genero--'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No binario', 'No binario'), ('Prefiero no decirlo', 'Prefiero no decirlo')], default=1, max_length=50)),
                ('Numero_De_Pasaporte', models.CharField(max_length=10)),
                ('Labor_en_Liquidacion', models.CharField(max_length=50)),
                ('Celular', models.IntegerField(max_length=9)),
                ('Email', models.EmailField(max_length=254)),
                ('Pensionado_por_Invalidez', models.BooleanField()),
                ('Profesional', models.BooleanField()),
                ('Tipo_de_impuesto_unico', models.CharField(choices=[('--Seleccione el tipo de impuesto--', '--Seleccione el tipo de impuesto--'), ('Normal', 'Normal'), ('Trabajador Agricola', 'Trabajador Agricola')], default=1, max_length=50)),
                ('Descuento_Prestamo_SII', models.BooleanField()),
            ],
        ),
    ]
