# Generated by Django 4.1.2 on 2023-07-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0002_alter_reserva_estado_alter_reserva_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='horareserva',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fechareserva',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
